name: Sentweet |>

on:
  push:
    branches:
    - master
    - feature/*

jobs:
  build:
    name: OS ${{matrix.os}} |> OTP ${{matrix.otp}} |> Elixir ${{matrix.elixir}} |> Node ${{matrix.node}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        otp: ['22.1', '23.0']
        elixir: ['1.10.0', '1.10.3']
        node: ['10.16.0']

    steps:
    - uses: actions/checkout@v2

    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node}}

    - name: Install Deps
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile

    - name: Build app
      run: |
        mix compile --warnings-as-errors
        mix format --check-formatted

    - name: Build release
      run: |
        mix phx.digest
        mix release
      env:
        MIX_ENV: prod
